export const GET_SCHOOL_EVENTS_REQUEST = "GET_SCHOOL_EVENTS_REQUEST";
export const GET_SCHOOL_EVENTS_SUCCESS = "GET_SCHOOL_EVENTS_SUCCESS";
export const GET_SCHOOL_EVENTS_FAIL = "GET_SCHOOL_EVENTS_FAIL";
