export const GET_ALL_SCHOOLS_REQUEST = "GET_ALL_SCHOOLS_REQUEST";
export const GET_ALL_SCHOOLS_SUCCESS = "GET_ALL_SCHOOLS_SUCCESS";
export const GET_ALL_SCHOOLS_FAIL = "GET_ALL_SCHOOLS_FAIL";

export const FEATURED_SCHOOLS_REQUEST = "FEATURED_SCHOOLS_REQUEST";
export const FEATURED_SCHOOLS_SUCCESS = "FEATURED_SCHOOLS_SUCCESS";
export const FEATURED_SCHOOLS_FAIL = "FEATURED_SCHOOLS_FAIL";
